name: macos_ui
description: Flutter widgets and themes implementing the current macOS design language.
version: 0.12.3
homepage: "https://github.com/GroovinChip/macos_ui"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.12.0
  mocktail: ^0.3.0

flutter:
